- name: Install System Packages
  apt:
    pkg:
      - software-properties-common
      - man
      - vim
      - wget
      - curl
      - snapd
      - ripgrep
      - make
    state: latest
    update_cache: true
  tags:
    - install
    - core
