- hosts: all
  pre_tasks:
  - name: Update Cache
    apt:
      update-cache: true
    tags:
      - core
      - network
      - docker
  - name: Wait for sudo
    become: yes
    shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
  tasks:
  - include: tasks/core.yml
  - include: tasks/network.yml
  - include: tasks/docker.yml

- name: Init Swarm Master
  hosts: masters
  gather_facts: False
  tasks:
    - name: Swarm Init
      command: docker swarm init --advertise-addr {{ inventory_hostname }}
    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token
    - name: Show Worker Token
      debug: var=worker_token.stdout
    - name: Master Token
      command: docker swarm join-token manager -q
      register: master_token
    - name: Show Master Token
      debug: var=master_token.stdout
    - name: Start Docker Swarm
      shell: cd ~/.scripts/swarm && docker stack deploy -c viz.yml viz
    - name: Start Infrastructure
      shell: cd ~/.scripts && docker-compose up -d

- name: Join Swarm Cluster
  hosts: workers
  gather_facts: False
  tags:
    - install
  vars:
    token: "{{ hostvars[groups['masters'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['masters'][0]]['inventory_hostname'] }}"
  tasks:
    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ token }} {{ master }}:2377
      register: worker
    - name: Show Results
      debug: var=worker.stdout
    - name: Show Errors
      debug: var=worker.stderr
