apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: infrastructure
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: aleksvagapitov@gmail.com # replace for your valid email
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik