apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: infra
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: my-registry:30000/custom-jenkins:lts
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: kubectl-config
          mountPath: /root/.kube/config
        env:
        - name: KUBECONFIG
          value: /root/.kube/config
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: kubectl-config
        hostPath:
          path: /root/.kube/jenkins-config
      nodeSelector:
        nodeName: jump-server
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: infra
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: jnlp
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins
  type: ClusterIP
